/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restapi.bookStorage.Book;

/**
 *
 * @author Paul
 */
import com.restapi.bookStorage.Test;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.ResponseBody;

@RestController
@RequestMapping(path = "/book")
public class BookController {

    @Autowired // This means to get the bean called bookRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BookRepository bookRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewBook(@RequestParam String name,
            @RequestParam String author, @RequestParam int barcode,
            @RequestParam int quantity, @RequestParam int price) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Optional<Book> books = bookRepository.findById(barcode);
        if (books.isEmpty()) {
            Book n = new Book(name, author, barcode, quantity, price);

            /*
            LOGGING TO FILE:
            */
            try (FileWriter fw = new FileWriter("BookLog.txt", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter out = new PrintWriter(bw)) {
                out.println("Added new book: Name=" + n.getName() + "," + "Author=" + n.getAuthor() + "," + "Barcode=" + n.getBarcode()
                        + "," + "Quantity=" + n.getQuantity() + "," + "Price=" + n.getPrice());
            } catch (IOException ex) {
                Logger.getLogger(BookController.class.getName()).log(Level.SEVERE, null, ex);
            };

            bookRepository.save(n);
            return "Saved";
        }
        else
            return "Book already exists. If you want to change the quantity or any other fields, go to UPDATE BOOK INFO.";
    }

    //GET book providing barcode
    @GetMapping("/get")
    public Optional<Book> getBook(@RequestParam(value = "barcode") int barcode) {
        return bookRepository.findById(barcode);
    }

    @PostMapping(path = "/update") // Map ONLY POST Requests
    public @ResponseBody
    String updateBook(@RequestParam String name,
            @RequestParam String author, @RequestParam int barcode,
            @RequestParam int quantity, @RequestParam int price) {

        //get book by barcode
        //set all fields which will be passed to book constructor
        //delete book by barcode
        //create new book with changed fields
        Optional<Book> oldBook = bookRepository.findById(barcode);
        if (!oldBook.isEmpty()) {
            String oldName = oldBook.get().getName();
            String oldAuthor = oldBook.get().getAuthor();
            int oldQuantity = oldBook.get().getQuantity();
            int oldPrice = oldBook.get().getPrice();

            if (!name.equals("null")) {
                oldName = name;
            }
            if (!author.equals("null")) {
                oldAuthor = author;
            }
            if (quantity != -1) {
                oldQuantity = quantity;
            }
            if (price != -1) {
                oldPrice = price;
            }

            //bookRepository.deleteById(barcode);
            Book n = new Book(oldName, oldAuthor, barcode, oldQuantity, oldPrice);

            bookRepository.save(n);
            return "Saved";
        } else {
            return "Book with entered barcode doesn't exist";
        }
    }

    //calculation of book price
    @GetMapping("/calculate")
    public @ResponseBody
    String calculateBookPrice(@RequestParam(value = "barcode") int barcode) {
        Optional<Book> books = bookRepository.findById(barcode);
        if (!books.isEmpty()) {
            int price = books.get().getPrice() * books.get().getQuantity();
            return "Total price of selected books=" + price;
        } else {
            return "This book doesn't exist";
        }
    }

    //for server and REST test purposes
    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    @GetMapping("/test")
    public Test greeting(@RequestParam(value = "name", defaultValue = "World") String name) {
        return new Test(counter.incrementAndGet(), String.format(template, name));
    }

}
