/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restapi.bookStorage.Journal;

/**
 *
 * @author Paul
 */
import com.restapi.bookStorage.Test;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.ResponseBody;

@RestController
@RequestMapping(path = "/journal")
public class JournalController {

    @Autowired // This means to get the bean called bookRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private JournalRepository journalRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addJournalBook(@RequestParam String name,
            @RequestParam String author, @RequestParam int barcode,
            @RequestParam int quantity, @RequestParam int price, @RequestParam int science_index) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Optional<Journal> books = journalRepository.findById(barcode);
        if (books.isEmpty()) {
            Journal n = new Journal(name, author, barcode, quantity, price, science_index);

            /*
            LOGGING TO FILE:
            */
            try (FileWriter fw = new FileWriter("JournalLog.txt", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter out = new PrintWriter(bw)) {
                out.println("Added new journal: Name=" + n.getName() + "," + "Author=" + n.getAuthor() + "," + "Barcode=" + n.getBarcode()
                        + "," + "Quantity=" + n.getQuantity() + "," + "Price=" + n.getPrice() + "," + "Science index=" + n.getIndex());
            } catch (IOException ex) {
                Logger.getLogger(JournalController.class.getName()).log(Level.SEVERE, null, ex);
            };

            journalRepository.save(n);
            return "Saved";
        }
        else
            return "Book already exists. If you want to change the quantity or any other fields, go to UPDATE BOOK INFO.";
    }

    //GET book providing barcode
    @GetMapping("/get")
    public Optional<Journal> getJournal(@RequestParam(value = "barcode") int barcode) {
        return journalRepository.findById(barcode);
    }

    @PostMapping(path = "/update") // Map ONLY POST Requests
    public @ResponseBody
    String updateJournal(@RequestParam String name,
            @RequestParam String author, @RequestParam int barcode,
            @RequestParam int quantity, @RequestParam int price, @RequestParam int science_index) {

        //get book by barcode
        //set all fields which will be passed to book constructor
        //delete book by barcode
        //create new book with changed fields
        Optional<Journal> oldBook = journalRepository.findById(barcode);
        if (!oldBook.isEmpty()) {
            String oldName = oldBook.get().getName();
            String oldAuthor = oldBook.get().getAuthor();
            int oldQuantity = oldBook.get().getQuantity();
            int oldPrice = oldBook.get().getPrice();
            int oldSc_index = oldBook.get().getIndex();

            if (name != null) {
                oldName = name;
            }
            if (author != null) {
                oldAuthor = author;
            }
            if (quantity != -1) {
                oldQuantity = quantity;
            }
            if (price != -1) {
                oldPrice = price;
            }
            if (science_index != -1) {
                oldSc_index = science_index;
            }

            //journalRepository.deleteById(barcode);

            Journal n = new Journal(oldName, oldAuthor, barcode, oldQuantity, oldPrice, oldSc_index);

            journalRepository.save(n);
            return "Saved";
        } else {
            return "Book with entered barcode doesn't exist";
        }
    }

    //calculation of book price
    @GetMapping("/calculate")
    public @ResponseBody
    String calculateBookPrice(@RequestParam(value = "barcode") int barcode) {
        Optional<Journal> journals = journalRepository.findById(barcode);
        if (!journals.isEmpty()) {
            int price = journals.get().getPrice() * journals.get().getQuantity() * journals.get().getIndex();
            return "Total price of selected books=" + price;
        } else {
            return "This book doesn't exist";
        }
    }

    //for server and REST test purposes
    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    @GetMapping("/test")
    public Test greeting(@RequestParam(value = "name", defaultValue = "World") String name) {
        return new Test(counter.incrementAndGet(), String.format(template, name));
    }

}
